import React from 'react';
import { FileText, ArrowLeft } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <button 
        onClick={onBack}
        className="flex items-center gap-2 text-indigo-600 hover:text-indigo-800 mb-8 transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        <span className="text-sm font-medium">Back to Home</span>
      </button>
      
      <div className="bg-white/80 backdrop-blur-xl rounded-3xl shadow-xl shadow-indigo-100/60 border border-white p-8 md:p-12">
        <div className="flex items-center gap-4 mb-8">
          <div className="p-3 bg-indigo-50 rounded-xl">
            <FileText className="h-8 w-8 text-indigo-600" />
          </div>
          <h1 className="text-4xl font-bold font-serif text-slate-900">Terms of Service</h1>
        </div>
        
        <p className="text-slate-500 text-sm mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        
        <div className="prose prose-slate max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Agreement to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing and using Alpha Quelle ("the Site"), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Description of Service</h2>
            <p className="text-slate-600 leading-relaxed">
              Alpha Quelle provides AI-powered sentiment analysis tools that aggregate and analyze publicly available information from news sources, earnings calls, and other public data feeds. Our service generates sentiment scores and signals based on natural language processing of this public data.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Financial Disclaimer</h2>
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-4">
              <p className="text-slate-700 leading-relaxed font-medium">
                <strong>IMPORTANT:</strong> Alpha Quelle is an informational and educational tool only. The content provided on this Site, including but not limited to sentiment analysis, signals, scores, and any other data or information, does NOT constitute:
              </p>
              <ul className="list-disc pl-6 text-slate-600 mt-4 space-y-2">
                <li>Financial advice or investment recommendations</li>
                <li>An offer or solicitation to buy or sell any securities</li>
                <li>Tax, legal, or accounting advice</li>
                <li>A recommendation or endorsement of any particular investment strategy</li>
              </ul>
            </div>
            <p className="text-slate-600 leading-relaxed">
              Trading stocks and other financial instruments involves substantial risk of loss and is not suitable for every investor. Past performance is not indicative of future results. You should consult with a qualified financial advisor, accountant, or attorney before making any investment decisions.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">No Guarantee of Accuracy</h2>
            <p className="text-slate-600 leading-relaxed">
              While we strive to provide accurate and timely information, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, analysis, or related graphics contained on the Site. The sentiment scores and signals are generated by artificial intelligence and may contain errors or inaccuracies.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Intellectual Property</h2>
            <p className="text-slate-600 leading-relaxed">
              The Site and its original content, features, and functionality are owned by Alpha Quelle and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">User Conduct</h2>
            <p className="text-slate-600 leading-relaxed mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 text-slate-600 space-y-2">
              <li>Use the Site for any unlawful purpose or in violation of any applicable laws</li>
              <li>Attempt to gain unauthorized access to any portion of the Site or any systems or networks connected to the Site</li>
              <li>Use any automated means to access the Site or collect any information from the Site</li>
              <li>Interfere with or disrupt the Site or servers or networks connected to the Site</li>
              <li>Reproduce, duplicate, copy, sell, resell, or exploit any portion of the Site without express written permission</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              In no event shall Alpha Quelle, its directors, employees, partners, agents, suppliers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Site.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Indemnification</h2>
            <p className="text-slate-600 leading-relaxed">
              You agree to defend, indemnify, and hold harmless Alpha Quelle and its licensee and licensors, and their employees, contractors, agents, officers, and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses arising from your use of and access to the Site.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Changes to Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right to modify or replace these Terms at any time at our sole discretion. By continuing to access or use our Site after those revisions become effective, you agree to be bound by the revised terms.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-serif font-bold text-slate-900 mb-4">Contact Us</h2>
            <p className="text-slate-600 leading-relaxed">
              If you have any questions about these Terms, please contact us at: <a href="mailto:legal@alphaquelle.com" className="text-indigo-600 hover:text-indigo-800 underline">legal@alphaquelle.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
